import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Starborn Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-Galaxy-Blue">
      <body>{children}</body>
    </html>
  );
}
